from datetime import datetime
import os

rev_id = f"a1b2c3d4e5f6"

content = f"""\"\"\"Add API Keys and Usage Logs

Revision ID: {rev_id}
Revises: 05ac55cf989f
Create Date: {datetime.now().isoformat()}

\"\"\"
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '{rev_id}'
down_revision: Union[str, None] = '05ac55cf989f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', 'enterprise', name='apitier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('request_method', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    sa.Enum(name='apitier').drop(op.get_bind())
    # ### end Alembic commands ###
"""

with open(f"backend/alembic/versions/{rev_id}_add_api_keys_and_usage_logs.py", "w") as f:
    f.write(content)

print("Migration file written.")
