import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldAlert } from 'lucide-react';
import { useAppStore } from '@/store/appStore';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetPath: string | null;
}

export function DisclaimerModal({ isOpen, onClose, targetPath }: DisclaimerModalProps) {
  const navigate = useNavigate();
  const { setDisclaimerAcknowledged } = useAppStore();

  const handleContinue = () => {
    setDisclaimerAcknowledged(true);
    onClose();
    if (targetPath) {
      navigate(targetPath);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="w-full max-w-lg bg-dark-surface border border-white/10 shadow-2xl rounded-xl overflow-hidden"
          >
            <div className="p-8">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-12 rounded-full bg-accent-gold/10 flex items-center justify-center">
                  <ShieldAlert className="w-6 h-6 text-accent-gold" />
                </div>
                <h2 className="text-2xl font-light text-white tracking-tight">Operational Intelligence Notice</h2>
              </div>

              <div className="space-y-4 text-dark-zinc-400 font-light leading-relaxed">
                <p>
                  TarkhaX provides AI-assisted operational analysis, workflow diagnostics, and maturity assessments intended for strategic and informational purposes only.
                </p>
                <p>
                  Outputs generated by the platform should not be treated as legal, regulatory, financial, or compliance advice. Organizations are responsible for validating recommendations before implementation.
                </p>
                <div className="bg-white/5 border border-white/10 p-4 rounded-lg mt-6">
                  <p className="text-sm text-dark-zinc-400">
                    <span className="text-white font-medium">Note:</span> No sensitive organizational data should be uploaded unless authorized by your organization's internal governance policies.
                  </p>
                </div>
              </div>
            </div>

            <div className="px-8 py-5 bg-black/40 border-t border-white/5 flex items-center justify-between">
              <p className="text-xs text-dark-zinc-500 max-w-[200px]">
                AI-generated operational insights may require human validation prior to implementation.
              </p>
              <div className="flex items-center gap-3">
                <button
                  onClick={onClose}
                  className="px-5 py-2 text-sm font-medium text-white/70 hover:text-white transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleContinue}
                  className="px-6 py-2 bg-accent-gold hover:bg-accent-gold/90 text-dark font-medium rounded-lg transition-colors shadow-[0_0_15px_rgba(212,183,106,0.3)]"
                >
                  Continue
                </button>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}