import React, { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useModalStore } from '@/store/modalStore';
import { cn } from '@/lib/utils';
import { ShieldAlert } from 'lucide-react';

export const OperationalNoticeModal: React.FC = () => {
  const navigate = useNavigate();
  const { isModalOpen, pendingRoute, setAcknowledged, closeModal, clearPendingRoute } = useModalStore();
  const modalRef = useRef<HTMLDivElement>(null);
  const continueBtnRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isModalOpen) return;

      if (e.key === 'Escape') {
        closeModal();
        clearPendingRoute();
      }

      if (e.key === 'Enter') {
        // If the user has tabbed to another button, let that button's click handler take over
        if (document.activeElement && document.activeElement.tagName === 'BUTTON' && document.activeElement !== continueBtnRef.current) {
          return;
        }
        e.preventDefault();
        handleContinue();
      }

      // Trap focus
      if (e.key === 'Tab') {
        const focusableElements = modalRef.current?.querySelectorAll(
          'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
        ) as NodeListOf<HTMLElement>;

        if (focusableElements && focusableElements.length > 0) {
          const firstElement = focusableElements[0];
          const lastElement = focusableElements[focusableElements.length - 1];

          if (e.shiftKey) {
            if (document.activeElement === firstElement) {
              lastElement.focus();
              e.preventDefault();
            }
          } else {
            if (document.activeElement === lastElement) {
              firstElement.focus();
              e.preventDefault();
            }
          }
        }
      }
    };

    if (isModalOpen) {
      document.addEventListener('keydown', handleKeyDown);
      // Prevent body scroll when modal is open
      document.body.style.overflow = 'hidden';
      // Focus the continue button on mount for accessibility
      setTimeout(() => continueBtnRef.current?.focus(), 50);
    }

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = 'unset';
    };
  }, [isModalOpen, pendingRoute]);

  const handleContinue = () => {
    setAcknowledged(true);
    closeModal();
    if (pendingRoute) {
      navigate(pendingRoute);
      clearPendingRoute();
    }
  };

  const handleLearnMore = () => {
    // Placeholder for Learn More logic
    alert("Navigating to governance/compliance information...");
  };

  if (!isModalOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/60 backdrop-blur-sm transition-all duration-300">
      <div
        ref={modalRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        aria-describedby="modal-description"
        className={cn(
          "w-full max-w-2xl bg-white border border-tarkha-gold/20 shadow-2xl rounded-lg flex flex-col",
          "transform transition-all duration-300 scale-100 opacity-100",
          "max-h-[90vh] overflow-y-auto"
        )}
      >
        <div className="flex-1 p-6 sm:p-10">
          <div className="flex items-center gap-4 mb-6">
            <div className="p-3 bg-tarkha-gold/10 rounded-full text-tarkha-gold">
              <ShieldAlert className="w-6 h-6" />
            </div>
            <h2 id="modal-title" className="text-2xl sm:text-3xl font-serif text-gray-900 tracking-tight">
              Operational Intelligence Notice
            </h2>
          </div>

          <div id="modal-description" className="space-y-6 text-gray-700">
            <div className="text-base sm:text-lg leading-relaxed font-sans space-y-4">
              <p>
                TarkhaX provides AI-assisted operational analysis, workflow diagnostics, and maturity assessments intended for strategic and informational purposes only.
              </p>
              <p>
                Outputs generated by the platform should not be treated as legal, regulatory, financial, or compliance advice. Organizations are responsible for validating recommendations before implementation.
              </p>
            </div>

            <div className="p-4 bg-tarkha-red/5 border-l-4 border-tarkha-red rounded-r-md">
              <p className="text-sm sm:text-base text-tarkha-red font-medium">
                No sensitive organizational data should be uploaded unless authorized by your organization's internal governance policies.
              </p>
            </div>
          </div>
        </div>

        <div className="px-6 py-5 sm:px-10 bg-gray-50 border-t border-gray-100 flex flex-col gap-4">
          <div className="flex flex-col sm:flex-row-reverse sm:justify-start gap-3">
            <button
              ref={continueBtnRef}
              onClick={handleContinue}
              className="w-full sm:w-auto px-6 py-3 bg-tarkha-gold hover:bg-tarkha-gold/90 text-white font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-tarkha-gold focus:ring-offset-2"
            >
              Continue
            </button>
            <button
              onClick={handleLearnMore}
              className="w-full sm:w-auto px-6 py-3 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-gray-200 focus:ring-offset-2"
            >
              Learn More
            </button>
          </div>

          <p className="text-xs text-gray-500 text-center sm:text-left">
            AI-generated operational insights may require human validation prior to implementation.
          </p>
        </div>
      </div>
    </div>
  );
};
