import { ProblemTemplate } from './ProblemTemplate';

export default function InconsistentAiPage() {
  return (
    <ProblemTemplate
      title="AI Outputs Are Inconsistent"
      seoTitle="Inconsistent AI Outputs"
      description="Sometimes the AI is brilliant. Sometimes it hallucinated. Discover why your team's prompts are failing and how to standardize them."
      symptoms={[
        "Customer support AI gives different answers to the same question.",
        "Content generated by AI sounds generic, off-brand, or robotic.",
        "Employees waste hours 'arguing' with the AI to get the right output.",
        "Compliance flags are being raised by automated outputs."
      ]}
      hiddenCauses={[
        "Employees lack structural prompt engineering skills and rely on 'chatting' rather than instructing.",
        "No centralized library of validated, successful prompts.",
        "Failure to provide the AI with sufficient contextual data (RAG limitations).",
        "Lack of defined evaluation criteria—teams don't know what 'good' looks like."
      ]}
      findingExample={{
        stat: "High variance in prompt structures across customer success team.",
        description: "Analysis of 500 prompts reveals that 80% lack explicit constraints, output formatting instructions, or brand voice context, leading to high rework rates.",
        impact: "Inconsistent brand experience and wasted employee hours on revisions."
      }}
      productLensUrl="/app/prompt-improver"
      productLensLabel="Try Prompt Improver"
    />
  );
}
