"""add_compliance_financial_future_fields_to_ai_systems

Revision ID: 0566ff918ed7
Revises: de1d3babcf77
Create Date: 2026-07-19 15:33:41.624105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0566ff918ed7'
down_revision: Union[str, Sequence[str], None] = 'de1d3babcf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_systems', sa.Column('applicable_regulations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('ai_systems', sa.Column('obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('ai_systems', sa.Column('evidence_status', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('cost', sa.Numeric(), nullable=True))
    op.add_column('ai_systems', sa.Column('roi_notes', sa.Text(), nullable=True))
    op.add_column('ai_systems', sa.Column('licensing_type', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('planned_changes', sa.Text(), nullable=True))
    op.add_column('ai_systems', sa.Column('roadmap_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_systems', 'roadmap_notes')
    op.drop_column('ai_systems', 'planned_changes')
    op.drop_column('ai_systems', 'licensing_type')
    op.drop_column('ai_systems', 'roi_notes')
    op.drop_column('ai_systems', 'cost')
    op.drop_column('ai_systems', 'evidence_status')
    op.drop_column('ai_systems', 'obligations')
    op.drop_column('ai_systems', 'applicable_regulations')
    # ### end Alembic commands ###
