"""add_roadmap_items

Revision ID: 076f4b8d7aa8
Revises: 69a1b2c3d4e5
Create Date: 2026-08-12 16:18:01.918337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "076f4b8d7aa8"
down_revision: Union[str, Sequence[str], None] = "69a1b2c3d4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmap_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("agent_recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("workflow_recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("time_horizon", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(opportunity_id IS NOT NULL AND agent_recommendation_id IS NULL AND workflow_recommendation_id IS NULL AND source_type = 'opportunity') OR (agent_recommendation_id IS NOT NULL AND opportunity_id IS NULL AND workflow_recommendation_id IS NULL AND source_type = 'agent_recommendation') OR (workflow_recommendation_id IS NOT NULL AND opportunity_id IS NULL AND agent_recommendation_id IS NULL AND source_type = 'workflow_recommendation')",
            name="check_roadmap_item_source_type_fk_alignment",
        ),
        sa.ForeignKeyConstraint(
            ["agent_recommendation_id"],
            ["agent_recommendations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_recommendation_id"],
            ["workflow_recommendations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_roadmap_items_agent_recommendation_id"),
        "roadmap_items",
        ["agent_recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_roadmap_items_opportunity_id"),
        "roadmap_items",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_roadmap_items_organization_id"),
        "roadmap_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_roadmap_items_workflow_recommendation_id"),
        "roadmap_items",
        ["workflow_recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_roadmap_items_workflow_recommendation_id"), table_name="roadmap_items"
    )
    op.drop_index(op.f("ix_roadmap_items_organization_id"), table_name="roadmap_items")
    op.drop_index(op.f("ix_roadmap_items_opportunity_id"), table_name="roadmap_items")
    op.drop_index(
        op.f("ix_roadmap_items_agent_recommendation_id"), table_name="roadmap_items"
    )
    op.drop_table("roadmap_items")
    # ### end Alembic commands ###
