"""Add ai_systems table

Revision ID: 4c2017c2d049
Revises: manual_005_add_user_token_and_verification
Create Date: 2026-07-18T17:46:22.263236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4c2017c2d049'
down_revision: Union[str, None] = 'manual_005_add_user_token_and_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_systems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('data_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_making_role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_organization_id'), 'ai_systems', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_systems_organization_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    # ### end Alembic commands ###
