"""add_workflow_recommendations

Revision ID: 69a1b2c3d4e5
Revises: 57c60c110565
Create Date: 2024-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1b2c3d4e5'
down_revision = '57c60c110565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('agent_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_recommendation_id'], ['agent_recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'recommendation_type', name='uix_opportunity_recommendation_type')
    )
    op.create_index(op.f('ix_workflow_recommendations_agent_recommendation_id'), 'workflow_recommendations', ['agent_recommendation_id'], unique=False)
    op.create_index(op.f('ix_workflow_recommendations_opportunity_id'), 'workflow_recommendations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_workflow_recommendations_organization_id'), 'workflow_recommendations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_recommendations_organization_id'), table_name='workflow_recommendations')
    op.drop_index(op.f('ix_workflow_recommendations_opportunity_id'), table_name='workflow_recommendations')
    op.drop_index(op.f('ix_workflow_recommendations_agent_recommendation_id'), table_name='workflow_recommendations')
    op.drop_table('workflow_recommendations')
    # ### end Alembic commands ###
