"""Add evidence and confidence fields

Revision ID: 6f5a34a2e5d9
Revises: 5ed348e4f775
Create Date: 2026-05-18 06:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5a34a2e5d9'
down_revision: Union[str, Sequence[str], None] = '5ed348e4f775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('evidence_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audits', sa.Column('evidence_quality_score', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('confidence_index', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'contradictions')
    op.drop_column('audits', 'confidence_index')
    op.drop_column('audits', 'evidence_quality_score')
    op.drop_column('audits', 'evidence_response')
    # ### end Alembic commands ###
