"""add industry_type to audits

Revision ID: 9f8e7d6c5b4a
Revises: add_contact_leads_table
Create Date: 2024-06-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8e7d6c5b4a'
down_revision: Union[str, Sequence[str], None] = 'manual_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    industry_type_enum = postgresql.ENUM('SAAS', 'FINTECH', 'BANKING', 'INSURANCE', 'HEALTHCARE', 'MANUFACTURING', 'EDUCATION', 'GOVERNMENT', 'RETAIL', 'LOGISTICS', name='industrytype')
    industry_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('audits', sa.Column('industry_type', industry_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'industry_type')
    industry_type_enum = postgresql.ENUM('SAAS', 'FINTECH', 'BANKING', 'INSURANCE', 'HEALTHCARE', 'MANUFACTURING', 'EDUCATION', 'GOVERNMENT', 'RETAIL', 'LOGISTICS', name='industrytype')
    industry_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
