"""add_data_intelligence_fields

Revision ID: c4d8881917c3
Revises: 3ff69d4ebaa6
Create Date: 2024-05-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c4d8881917c3'
down_revision: Union[str, None] = "ac9f724e0bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_systems', sa.Column('data_quality_notes', sa.Text(), nullable=True))
    op.add_column('ai_systems', sa.Column('data_owner', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('data_freshness', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('data_accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('ai_systems', sa.Column('data_availability', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_systems', 'data_availability')
    op.drop_column('ai_systems', 'data_accessibility')
    op.drop_column('ai_systems', 'data_freshness')
    op.drop_column('ai_systems', 'data_owner')
    op.drop_column('ai_systems', 'data_quality_notes')
    # ### end Alembic commands ###
