"""add system_findings table

Revision ID: c7b4b8d46cba
Revises: ca6463a714d3
Create Date: 2026-07-20 10:41:45.916091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c7b4b8d46cba'
down_revision: Union[str, Sequence[str], None] = 'ca6463a714d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('ai_system_id', sa.Uuid(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_findings_audit_id'), 'system_findings', ['audit_id'], unique=False)
    op.create_index(op.f('ix_system_findings_ai_system_id'), 'system_findings', ['ai_system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_findings_ai_system_id'), table_name='system_findings')
    op.drop_index(op.f('ix_system_findings_audit_id'), table_name='system_findings')
    op.drop_table('system_findings')
    # ### end Alembic commands ###
