"""add_governance_and_security_fields_to_ai_systems

Revision ID: de1d3babcf77
Revises: c812aa03f90a
Create Date: 2026-07-19 15:23:27.848642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'de1d3babcf77'
down_revision: Union[str, Sequence[str], None] = 'c812aa03f90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_systems', sa.Column('risk_classification', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('oversight_status', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('documentation_status', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('applicable_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('ai_systems', sa.Column('rbac_enabled', sa.Boolean(), nullable=True))
    op.add_column('ai_systems', sa.Column('encryption_status', sa.String(), nullable=True))
    op.add_column('ai_systems', sa.Column('incident_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_systems', 'incident_count')
    op.drop_column('ai_systems', 'encryption_status')
    op.drop_column('ai_systems', 'rbac_enabled')
    op.drop_column('ai_systems', 'applicable_policies')
    op.drop_column('ai_systems', 'documentation_status')
    op.drop_column('ai_systems', 'oversight_status')
    op.drop_column('ai_systems', 'risk_classification')
    # ### end Alembic commands ###
