"""add audit_id and org_id to export_jobs

Revision ID: manual_004
Revises: manual_003
Create Date: 2026-06-08 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'manual_004'
down_revision: Union[str, Sequence[str], None] = 'manual_003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('audit_id', sa.Uuid(), nullable=True))
    op.add_column('export_jobs', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_export_jobs_audit_id_audits', 'export_jobs', 'audits', ['audit_id'], ['id'])
    op.create_foreign_key('fk_export_jobs_org_id_organizations', 'export_jobs', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_export_jobs_org_id_organizations', 'export_jobs', type_='foreignkey')
    op.drop_constraint('fk_export_jobs_audit_id_audits', 'export_jobs', type_='foreignkey')
    op.drop_column('export_jobs', 'org_id')
    op.drop_column('export_jobs', 'audit_id')
    # ### end Alembic commands ###
