import { SeoHead } from '../../components/geo/SeoHead';

export default function AiDisclaimerPage() {
  return (
    <div className="bg-bg-primary min-h-screen animate-fade-up">
      <SeoHead
        title="AI Transparency Disclaimer | TarkaX"
        description="Important information regarding the use of AI on the TarkaX platform."
        canonical="https://tarkax.com/ai-disclaimer"
      />
      <div className="max-w-3xl mx-auto py-24 px-6">
        <h1 className="text-h1 font-semibold mb-8 border-b border-border-light pb-4">AI Transparency Disclaimer</h1>
        <div className="prose text-body text-text-secondary space-y-6">
          <div className="mb-8 p-4 bg-bg-secondary rounded-lg border border-border-light">
            <p className="font-medium text-text-primary m-0">Version: v1.0</p>
            <p className="font-medium text-text-primary m-0">Effective Date: June 06, 2026</p>
            <p className="font-medium text-text-primary m-0">Last Updated: June 06, 2026</p>
          </div>

          <h2 className="text-h2 font-medium text-text-primary mt-8">1. AI-Assisted Systems</h2>
          <p>By using the TarkaX platform, you acknowledge that you are interacting with AI-assisted systems. The intelligence, diagnostic outputs, and risk projections provided by TarkaX are generated or assisted by artificial intelligence and automated deterministic engines.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">2. Output Limitations</h2>
          <p>While we strive for accuracy through our deterministic rule engines, the outputs generated by our AI-assisted systems may be inaccurate, incomplete, or not fully applicable to your specific organizational context.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">3. Human Review Required</h2>
          <p>Human review is strongly recommended before reliance on any output generated by TarkaX. The insights provided should serve as a supplementary tool for decision-making and must not replace professional judgment.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">4. Nature of Information</h2>
          <p>All outputs provided by TarkaX are purely informational. TarkaX does not provide, and the outputs should not be treated as, legal, financial, investment, compliance, or professional advice. Always consult with qualified professionals for specific advice related to your business operations.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">5. EU AI Act Transparency</h2>
          <p>In compliance with transparency requirements, users are explicitly informed that they are interacting with an AI system. The purpose of this system is to analyze operational data and provide diagnostic insights. Users retain the responsibility to interpret and apply these insights appropriately within their operational contexts.</p>
        </div>
      </div>
    </div>
  );
}
