import { SeoHead } from '../../components/geo/SeoHead';

export default function DataRetentionPage() {
  return (
    <div className="bg-bg-primary min-h-screen animate-fade-up">
      <SeoHead
        title="Data Retention Policy | TarkaX"
        description="Data retention periods and practices for the TarkaX platform."
        canonical="https://tarkax.com/data-retention"
      />
      <div className="max-w-3xl mx-auto py-24 px-6">
        <h1 className="text-h1 font-semibold mb-8 border-b border-border-light pb-4">Data Retention Policy</h1>
        <div className="prose text-body text-text-secondary space-y-6">
          <div className="mb-8 p-4 bg-bg-secondary rounded-lg border border-border-light">
            <p className="font-medium text-text-primary m-0">Version: v1.0</p>
            <p className="font-medium text-text-primary m-0">Effective Date: June 06, 2026</p>
            <p className="font-medium text-text-primary m-0">Last Updated: June 06, 2026</p>
          </div>

          <h2 className="text-h2 font-medium text-text-primary mt-8">1. Introduction</h2>
          <p>TarkaX is committed to minimizing the data we store and retaining it only for as long as necessary to fulfill the purposes for which it was collected, comply with our legal obligations, resolve disputes, and enforce our agreements. This policy outlines the specific retention periods for different categories of data.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">2. Retention Periods by Data Category</h2>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Account Data</h3>
          <p><strong>Description:</strong> User profiles, names, email addresses, company names, and authentication credentials.</p>
          <p><strong>Retention Period:</strong> Retained for the active duration of the user's account. Upon account deletion request, account data is permanently deleted within 30 days, except where retention is required by law.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Audit Data</h3>
          <p><strong>Description:</strong> Responses and inputs provided during AI Audits.</p>
          <p><strong>Retention Period:</strong> Retained for 24 months from the date the audit was completed to allow for year-over-year operational comparisons, or until the user requests deletion.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Workflow Data</h3>
          <p><strong>Description:</strong> Inputs, diagnostic configurations, and structural data provided during Workflow Diagnostics.</p>
          <p><strong>Retention Period:</strong> Retained for 24 months from the date of the workflow analysis to support historical diagnostic comparisons, or until the user requests deletion.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Prompt Data</h3>
          <p><strong>Description:</strong> Inputs and text submitted via the Prompt Improver features.</p>
          <p><strong>Retention Period:</strong> Retained temporarily for processing and deleted within 90 days, as this feature focuses on immediate improvement rather than long-term historical analysis.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Contact Form Data</h3>
          <p><strong>Description:</strong> Inquiries, names, and emails submitted through public contact forms.</p>
          <p><strong>Retention Period:</strong> Retained for up to 12 months from the date of the last communication to ensure proper follow-up and customer service resolution.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Analytics Data</h3>
          <p><strong>Description:</strong> Aggregated usage metrics, interaction events, and performance data collected via third-party analytics tools (e.g., Google Analytics, Vercel Analytics).</p>
          <p><strong>Retention Period:</strong> Retained according to the default retention policies of the respective analytics providers, typically not exceeding 14 months.</p>

          <h3 className="text-h3 font-medium text-text-primary mt-6">Logs</h3>
          <p><strong>Description:</strong> System logs, access logs, and error logs generated by our servers.</p>
          <p><strong>Retention Period:</strong> Retained for up to 90 days for security monitoring, debugging, and incident response purposes.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">3. Data Deletion Requests</h2>
          <p>Users may request the deletion of their data at any time by contacting privacy@tarkax.com. Subject to identity verification and legal requirements, we will process deletion requests within 30 days.</p>
        </div>
      </div>
    </div>
  );
}
