import React from 'react';
import { ShieldCheck, Target, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function MethodologyPage() {
  return (
    <div style={{ background: 'var(--tx-bg-card)' }}>
      {/* Hero Section */}
      <section className="text-white py-20" style={{ background: 'var(--tx-bg-dark)' }}>
        <div className="container mx-auto px-4 max-w-4xl text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">The TarkaX Methodology</h1>
          <p className="text-xl text-slate-300 mb-8">
            An evidence-based approach to measuring organizational readiness, execution risk, and operational capability.
          </p>
        </div>
      </section>

      {/* Core Principles */}
      <section className="py-20">
        <div className="container mx-auto px-4 max-w-5xl">
          <div className="mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-6">Our Core Principle: Explainable Intelligence</h2>
            <p className="text-lg text-slate-600 mb-6">
              Organizations don't fail because they lack tools; they fail because of misaligned strategies, governance gaps, and execution friction. The TarkaX Methodology uses deterministic, rule-based engines to identify these structural risks before they become institutional failures.
            </p>
            <p className="text-lg text-slate-600">
              We explicitly reject "black-box" AI scoring. Every score, finding, and recommendation generated by TarkaX can be traced back to specific operational contradictions and evidenced capability gaps.
            </p>
          </div>

          {/* The 5 Dimensions */}
          <div className="mb-20">
            <h2 className="text-3xl font-bold text-slate-900 mb-10">The 5 Dimensions of Operational Health</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-slate-50 p-8 rounded-lg border border-slate-100">
                <h3 className="text-xl font-bold text-slate-900 mb-3">1. Awareness</h3>
                <p className="text-slate-600">Measures the depth of strategic understanding and literacy across the organization. Are teams aligned on the "why"?</p>
              </div>
              <div className="bg-slate-50 p-8 rounded-lg border border-slate-100">
                <h3 className="text-xl font-bold text-slate-900 mb-3">2. Adoption</h3>
                <p className="text-slate-600">Measures the practical application of strategy. Are teams actually utilizing the capabilities they possess?</p>
              </div>
              <div className="bg-slate-50 p-8 rounded-lg border border-slate-100">
                <h3 className="text-xl font-bold text-slate-900 mb-3">3. Integration</h3>
                <p className="text-slate-600">Measures structural connectedness. Are tools, data, and processes seamlessly linked, or are they isolated silos?</p>
              </div>
              <div className="bg-slate-50 p-8 rounded-lg border border-slate-100">
                <h3 className="text-xl font-bold text-slate-900 mb-3">4. Governance</h3>
                <p className="text-slate-600">Measures risk management and oversight. Are there clear policies, approvals, and compliance safeguards in place?</p>
              </div>
              <div className="bg-slate-50 p-8 rounded-lg border border-slate-100 md:col-span-2">
                <h3 className="text-xl font-bold text-slate-900 mb-3">5. ROI (Return on Investment)</h3>
                <p className="text-slate-600">Measures value realization. Can the organization definitively prove that their operations are yielding strategic or financial value?</p>
              </div>
            </div>
          </div>

          {/* How We Score */}
          <div className="mb-20">
            <h2 className="text-3xl font-bold text-slate-900 mb-6">How We Score</h2>
            <div className="bg-blue-50 border border-blue-100 p-8 rounded-lg">
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <ShieldCheck className="w-6 h-6 text-blue-600" />
                Deterministic Scoring
              </h3>
              <p className="text-slate-700 mb-6">
                Our scoring engine evaluates responses against the TarkaX Maturity Model. It looks for <strong>Contradictions</strong> (e.g., claiming high adoption but having zero governance) to adjust scores and build a <strong>Confidence Index</strong>.
              </p>
              <ul className="space-y-4">
                <li className="flex items-start gap-3">
                  <Target className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                  <span className="text-slate-700"><strong>Level 1 (Fragile):</strong> Ad-hoc, heroic efforts. Highly vulnerable to failure.</span>
                </li>
                <li className="flex items-start gap-3">
                  <Target className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                  <span className="text-slate-700"><strong>Level 3 (Operational):</strong> Documented, repeatable, and actively managed.</span>
                </li>
                <li className="flex items-start gap-3">
                  <Target className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                  <span className="text-slate-700"><strong>Level 5 (Resilient):</strong> Deeply integrated, predictive, and self-healing.</span>
                </li>
              </ul>
            </div>
          </div>

          {/* CTA */}
          <div className="text-center text-white rounded-xl p-12" style={{ background: 'var(--tx-bg-dark)' }}>
            <h2 className="text-2xl font-bold mb-4">See the Methodology in Action</h2>
            <p className="text-slate-300 mb-8 max-w-2xl mx-auto">
              Run an assessment to see exactly how our intelligence engine maps capability gaps to business risks.
            </p>
            <Link
              to="/ai-audit"
              className="inline-flex items-center justify-center text-slate-900 px-6 py-3 rounded-md font-medium hover:bg-slate-100 transition-colors" style={{ background: 'var(--tx-bg-card)' }}
            >
              Start Free Assessment <ArrowRight className="ml-2 w-4 h-4" />
            </Link>
          </div>

        </div>
      </section>
    </div>
  );
}
