import { SeoHead } from '../../components/geo/SeoHead';

export default function TermsPage() {
  return (
    <div className="bg-bg-primary min-h-screen animate-fade-up">
      <SeoHead
        title="Terms of Service | TarkaX"
        description="Terms of service and acceptable use for the TarkaX platform."
        canonical="https://tarkax.com/terms"
      />
      <div className="max-w-3xl mx-auto py-24 px-6">
        <h1 className="text-h1 font-semibold mb-8 border-b border-border-light pb-4">Terms of Service</h1>
        <div className="prose text-body text-text-secondary space-y-6">
          <p>Last Updated: {new Date().toLocaleDateString()}</p>
          <h2 className="text-h2 font-medium text-text-primary mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using the TarkaX platform, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">2. Use License</h2>
          <p>TarkaX grants you a limited, non-exclusive, non-transferable license to use the intelligence reports generated by the platform solely for internal organizational purposes.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">3. Assessment Accuracy</h2>
          <p>TarkaX relies on self-reported data. The insights generated are indicators of operational risk and capability gaps, but do not replace comprehensive audits by certified professionals.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">4. Limitations</h2>
          <p>In no event shall TarkaX be liable for any damages arising out of the use or inability to use the materials on TarkaX's platform.</p>
        </div>
      </div>
    </div>
  );
}
