import { SeoHead } from '../../components/geo/SeoHead';

export default function TermsPage() {
  return (
    <div className="bg-bg-primary min-h-screen animate-fade-up">
      <SeoHead
        title="Terms of Service | TarkaX"
        description="Terms of service and acceptable use for the TarkaX platform."
        canonical="https://tarkax.com/terms"
      />
      <div className="max-w-3xl mx-auto py-24 px-6">
        <h1 className="text-h1 font-semibold mb-8 border-b border-border-light pb-4">Terms of Service</h1>
        <div className="prose text-body text-text-secondary space-y-6">
          <div className="mb-8 p-4 bg-bg-secondary rounded-lg border border-border-light">
            <p className="font-medium text-text-primary m-0">Version: v1.0</p>
            <p className="font-medium text-text-primary m-0">Effective Date: June 06, 2026</p>
            <p className="font-medium text-text-primary m-0">Last Updated: June 06, 2026</p>
          </div>

          <h2 className="text-h2 font-medium text-text-primary mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using the TarkaX platform, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not access the service.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">2. Service Description</h2>
          <p>TarkaX is a Subscription SaaS Operational Intelligence Platform. The service provides capabilities including AI Audit, Workflow Diagnostic, Risk Projection, Failure Intelligence, and Prompt Improver (in development). The platform offers both free and paid plans, with future plans for API access.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">3. Account Requirements and Age Restriction</h2>
          <p>You must be at least 18 years old to create an account and use the TarkaX platform. By creating an account, you represent and warrant that you are at least 18 years of age.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">4. User Responsibilities</h2>
          <p>You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree not to use the service for any illegal or unauthorized purpose.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">5. Intellectual Property</h2>
          <p>The TarkaX platform, including its original content, features, and functionality, is owned by TarkaX and is protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">6. Subscription and API Future Usage</h2>
          <p>Access to certain features of TarkaX may require a paid subscription. Subscription terms, including billing cycles and cancellation policies, are provided at the time of purchase. TarkaX may offer API access in the future, subject to additional terms and conditions that will be provided at that time.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">7. AI Output Limitations</h2>
          <p>The TarkaX platform utilizes AI-assisted systems. The outputs generated by the service are for informational purposes only. Outputs may be inaccurate, incomplete, and require human review. The service does not provide legal, financial, compliance, investment, or professional advice. TarkaX is not responsible for decisions made based on the outputs generated by the platform.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">8. Service Availability Disclaimer</h2>
          <p>TarkaX is provided on an "AS IS" and "AS AVAILABLE" basis. TarkaX makes no representations or warranties of any kind, express or implied, as to the operation of their services, or the information, content, or materials included therein.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">9. Limitation of Liability and Consequential Damages Exclusion</h2>
          <p>In no event shall TarkaX be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">10. Governing Law and Arbitration</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of [Governing Law Placeholder], without regard to its conflict of law provisions.</p>
          <p>Any dispute arising from or relating to the subject matter of these Terms shall be finally settled by arbitration in [Arbitration Placeholder].</p>

          <h2 className="text-h2 font-medium text-text-primary mt-8">11. Changes to Terms</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any material changes by updating the "Effective Date" of these Terms.</p>
        </div>
      </div>
    </div>
  );
}
