import { useEffect, useRef } from 'react';
import { cn } from '@/lib/utils';

interface OperationalNoticeModalProps {
  isOpen: boolean;
  onContinue: () => void;
  onClose: () => void;
}

export function OperationalNoticeModal({
  isOpen,
  onContinue,
  onClose,
}: OperationalNoticeModalProps) {
  const modalRef = useRef<HTMLDivElement>(null);

  // Close on ESC key
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  // Trap focus (simple version - focus the modal when it opens)
  useEffect(() => {
    if (isOpen && modalRef.current) {
      modalRef.current.focus();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      aria-modal="true"
      role="dialog"
      aria-labelledby="modal-title"
    >
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/80 backdrop-blur-sm transition-opacity"
        aria-hidden="true"
        onClick={onClose}
      />

      {/* Modal Container */}
      <div
        ref={modalRef}
        tabIndex={-1}
        className={cn(
          'relative z-10 w-full max-w-lg overflow-hidden rounded-xl',
          'bg-[#141414] text-zinc-100 shadow-2xl outline-none',
          'border border-white/5 ring-1 ring-white/10',
          'transform opacity-100 scale-100 transition-all duration-300 ease-out'
        )}
      >
        {/* Subtle Gold Accent Line */}
        <div className="h-1 w-full bg-gradient-to-r from-transparent via-amber-500/50 to-transparent opacity-80" />

        <div className="px-8 py-10">
          <h2
            id="modal-title"
            className="mb-6 text-2xl font-light tracking-wide text-zinc-50"
          >
            AI Governance Notice
          </h2>

          <div className="space-y-6 text-[15px] leading-relaxed text-zinc-300">
            <p>
              TarkhaX provides AI-assisted operational analysis, workflow diagnostics,
              and maturity assessments intended for strategic and informational purposes
              only.
            </p>
            <p>
              Outputs generated by the platform should not be treated as legal,
              regulatory, financial, or compliance advice. Organizations are responsible
              for validating recommendations before implementation.
            </p>
            <p className="border-l-2 border-white/10 pl-4 text-sm text-zinc-400 italic">
              No sensitive organizational data should be uploaded unless authorized by
              your organization&apos;s internal governance policies.
            </p>
          </div>
        </div>

        {/* Footer / Actions */}
        <div className="flex flex-col-reverse justify-end gap-3 bg-white/5 px-8 py-6 sm:flex-row sm:items-center">
          <button
            onClick={onClose}
            className={cn(
              'rounded-md px-5 py-2.5 text-sm font-medium tracking-wide transition-colors',
              'text-zinc-400 hover:bg-white/5 hover:text-zinc-200 focus:outline-none focus:ring-2 focus:ring-zinc-500'
            )}
          >
            Learn More
          </button>
          <button
            onClick={onContinue}
            className={cn(
              'group relative overflow-hidden rounded-md px-6 py-2.5 text-sm font-medium tracking-wide transition-all',
              'bg-amber-600/90 text-amber-50 shadow-[0_0_15px_rgba(217,119,6,0.3)] hover:bg-amber-500 hover:shadow-[0_0_20px_rgba(217,119,6,0.5)]',
              'focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2 focus:ring-offset-[#141414]'
            )}
          >
            <span className="relative z-10">Continue</span>
            <div className="absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent transition-transform duration-700 ease-in-out group-hover:translate-x-full" />
          </button>
        </div>
      </div>
    </div>
  );
}
